# volumes:
#   react:
#     name: react
#     driver_opts:
#       type: none
#       device: src/
#       o: bind
#   nestjs:
#     name: nestjs
#     driver_opts:
#       type: none
#       device: src_nestjs/
#       o: bind

services:
  react:
    container_name: react
    image: react
    build: dockerfiles/react
    ports:
      - "3000:3000"
    volumes:
      - ./react:/home/root/transcendence/
    restart: on-failure
    networks:
      - transcendence
  postgres:
    container_name: postgres
    image: postgres
    command: postgres -c stats_temp_directory=/tmp # prevent warnings about pg_stats: https://stackoverflow.com/questions/66325175/docker-container-with-postgres-warning-could-not-open-statistics-file-pg-stat
    # build: dockerfiles/postgres
    ports:
      - "5432:5432"
    env_file:
      - ./dockerfiles/postgres/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - transcendence
  nestjs:
    container_name: nestjs
    image: nestjs
    build: dockerfiles/nestjs
    # depends_on:
    #   - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./nestjs:/home/root/transcendence_backend/
    restart: on-failure
    networks:
      - transcendence
    environment:
      - SERVER_LOCATION
      - MYHOSTNAME

    
networks: 
  transcendence:
