volumes:
  react:
    name: react
    driver_opts:
      type: none
      device: src/
      o: bind
  nestjs:
    name: nestjs
    driver_opts:
      type: none
      device: src_nestjs/
      o: bind

services:
  react:
    image: react
    build: dockerfiles/react
    ports:
      - "3000:3000"
    volumes:
      - react:/home/root/transcendence/src
    restart: on-failure
  nestjs:
    image: nestjs
    build: dockerfiles/nestjs
    ports:
      - "5000:5000"
    volumes:
      - nestjs:/home/root/transcendence_backend/src
    restart: on-failure

