volumes:
  react:
    name: react
    driver_opts:
      type: none
      device: src/
      o: bind
  nestjs:
    name: nestjs
    driver_opts:
      type: none
      device: src_nestjs/
      o: bind

services:
  react:
    container_name: react
    image: react
    build: dockerfiles/react
    ports:
      - "3000:3000"
    volumes:
      - react:/home/root/transcendence/src
    restart: on-failure
    networks:
      - transcendence
  nestjs:
    container_name: nestjs
    image: nestjs
    build: dockerfiles/nestjs
    ports:
      - "5000:5000"
    volumes:
      - nestjs:/home/root/transcendence_backend/src
    restart: on-failure
    networks:
      - transcendence
  postgres:
    container_name: postgres
    image: postgres
    build: dockerfiles/postgres
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - transcendence
    
networks: 
  transcendence:
